version: '3.5'

services:
  web:
    build: .
    volumes:
      - .:/opt/services/app/src
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - nginx_network
      - redis_network
      - database1_network
    ports:
      - 8000:8000
    depends_on:
      - database1
      - redis

  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    networks:
      - redis_network

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  redis_network:
    driver: bridge
  database1_network:
    driver: bridge

volumes:
  database1_volume:
