version: '3.5'

services:
  web:
    deploy:
      placement:
        constraints:
          - node.hostname == manager1

  nginx:
    deploy:
      placement:
        constraints:
          - node.hostname == manager1

  redis:
    deploy:
      placement:
        constraints:
          - node.hostname == manager1
